name: Publish to NPM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build
      run: bun run build
      continue-on-error: true  # Continue even if existing TS errors

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Determine and bump version
      id: version
      run: |
        # Get last commit message
        COMMIT_MSG=$(git log -1 --pretty=%B)
        
        # Extract current version
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        # Determine bump type
        if [[ $COMMIT_MSG =~ \[major\] ]]; then
          BUMP_TYPE="major"
        elif [[ $COMMIT_MSG =~ \[minor\] ]]; then
          BUMP_TYPE="minor"
        else
          BUMP_TYPE="patch"
        fi
        
        echo "Bump type: $BUMP_TYPE"
        
        # Bump version and capture new version
        NEW_VERSION=$(npm version $BUMP_TYPE --no-git-tag-version)
        echo "New version: $NEW_VERSION"
        
        # Set output for later steps
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT

    - name: Commit version bump
      run: |
        git add package.json
        git commit -m "Bump version to ${{ steps.version.outputs.new_version }} [skip ci]"

    - name: Create and push tag
      run: |
        git tag ${{ steps.version.outputs.new_version }}
        git push origin main
        git push origin ${{ steps.version.outputs.new_version }}

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}